<<<<<<< Updated upstream
// Generated by Bisonc++ V6.01.00 on Mon, 22 Apr 2024 15:40:03 +0000
=======
// Generated by Bisonc++ V6.01.00 on Sat, 01 Jun 2024 18:57:42 +0000
>>>>>>> Stashed changes

// base/comment

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token is Reserved__::UNDETERMINED__, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on errTok__
// which is applied. In this errTok__ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
//      }

// base/declarations

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum Reserved__
    {
        UNDETERMINED__   = -2,
        EOF__            = -1,
        errTok__         = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    enum StateTransition
    {
        ACCEPT__   = 0,     // `ACCEPT' TRANSITION
    };

    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            StateType d_type;
            int       d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {322, 1}, // 1: program ->  exp
     {323, 1}, // 2: exp (INT) ->  INT
     {323, 1}, // 3: exp (STRING) ->  STRING
     {323, 1}, // 4: exp (NIL) ->  NIL
     {323, 1}, // 5: exp ->  lvalue
     {323, 2}, // 6: exp (ID) ->  ID rec
     {323, 6}, // 7: exp (ID) ->  ID LBRACK exp RBRACK OF exp
     {323, 4}, // 8: exp (ID) ->  ID LPAREN actuals RPAREN
     {323, 3}, // 9: exp (ASSIGN) ->  lvalue ASSIGN exp
     {323, 4}, // 10: exp (IF) ->  IF exp THEN exp
     {323, 6}, // 11: exp (IF) ->  IF exp THEN exp ELSE exp
     {323, 4}, // 12: exp (WHILE) ->  WHILE exp DO exp
     {323, 8}, // 13: exp (FOR) ->  FOR ID ASSIGN exp TO exp DO exp
     {323, 1}, // 14: exp (BREAK) ->  BREAK
     {323, 5}, // 15: exp (LET) ->  LET decs IN expseq END
     {323, 3}, // 16: exp (PLUS) ->  exp PLUS exp
     {323, 3}, // 17: exp (MINUS) ->  exp MINUS exp
     {323, 3}, // 18: exp (TIMES) ->  exp TIMES exp
     {323, 3}, // 19: exp (DIVIDE) ->  exp DIVIDE exp
     {323, 3}, // 20: exp (EQ) ->  exp EQ exp
     {323, 3}, // 21: exp (NEQ) ->  exp NEQ exp
     {323, 3}, // 22: exp (LE) ->  exp LE exp
     {323, 3}, // 23: exp (LT) ->  exp LT exp
     {323, 3}, // 24: exp (GT) ->  exp GT exp
     {323, 3}, // 25: exp (GE) ->  exp GE exp
     {323, 3}, // 26: exp (AND) ->  exp AND exp
     {323, 3}, // 27: exp (OR) ->  exp OR exp
     {323, 2}, // 28: exp (MINUS) ->  MINUS exp
     {323, 3}, // 29: exp (LPAREN) ->  LPAREN exp RPAREN
     {323, 2}, // 30: exp (LPAREN) ->  LPAREN RPAREN
     {323, 1}, // 31: exp ->  sequencing
     {324, 1}, // 32: lvalue (ID) ->  ID
     {324, 3}, // 33: lvalue (DOT) ->  lvalue DOT ID
     {324, 4}, // 34: lvalue (LBRACK) ->  lvalue LBRACK exp RBRACK
     {324, 4}, // 35: lvalue (ID) ->  ID LBRACK exp RBRACK
     {325, 1}, // 36: sequencing_exps ->  exp
     {325, 3}, // 37: sequencing_exps (SEMICOLON) ->  exp SEMICOLON sequencing_exps
     {326, 3}, // 38: sequencing (LPAREN) ->  LPAREN sequencing_exps RPAREN
     {327, 1}, // 39: expseq ->  sequencing_exps
     {328, 1}, // 40: nonemptyactuals ->  exp
     {328, 3}, // 41: nonemptyactuals (COMMA) ->  exp COMMA actuals
     {329, 1}, // 42: actuals ->  nonemptyactuals
     {329, 0}, // 43: actuals ->  <empty>
     {330, 1}, // 44: decs_nonempty_s ->  tydec
     {330, 1}, // 45: decs_nonempty_s ->  vardec
     {330, 1}, // 46: decs_nonempty_s ->  fundec
     {331, 1}, // 47: decs_nonempty ->  decs_nonempty_s
     {331, 2}, // 48: decs_nonempty ->  decs_nonempty_s decs_nonempty
     {332, 1}, // 49: decs ->  decs_nonempty
     {333, 4}, // 50: tydec_one (TYPE) ->  TYPE ID EQ ty
     {334, 1}, // 51: tydec ->  tydec_one
     {334, 2}, // 52: tydec ->  tydec_one tydec
     {335, 6}, // 53: vardec (VAR) ->  VAR ID COLON ID ASSIGN exp
     {335, 4}, // 54: vardec (VAR) ->  VAR ID ASSIGN exp
     {336, 1}, // 55: ty (ID) ->  ID
     {336, 3}, // 56: ty (LBRACE) ->  LBRACE tyfields RBRACE
     {336, 3}, // 57: ty (ARRAY) ->  ARRAY OF ID
     {337, 3}, // 58: tyfield (ID) ->  ID COLON ID
     {338, 1}, // 59: tyfields_nonempty ->  tyfield
     {338, 3}, // 60: tyfields_nonempty (COMMA) ->  tyfield COMMA tyfields
     {339, 1}, // 61: tyfields ->  tyfields_nonempty
     {339, 0}, // 62: tyfields ->  <empty>
     {340, 3}, // 63: rec_one (ID) ->  ID EQ exp
     {341, 1}, // 64: rec_nonempty ->  rec_one
     {341, 3}, // 65: rec_nonempty (COMMA) ->  rec_one COMMA rec_nonempty
     {342, 3}, // 66: rec (LBRACE) ->  LBRACE rec_nonempty RBRACE
     {342, 2}, // 67: rec (LBRACE) ->  LBRACE RBRACE
     {343, 9}, // 68: fundec_one (FUNCTION) ->  FUNCTION ID LPAREN tyfields RPAREN COLON ID EQ exp
     {343, 7}, // 69: fundec_one (FUNCTION) ->  FUNCTION ID LPAREN tyfields RPAREN EQ exp
     {344, 1}, // 70: fundec ->  fundec_one
     {344, 2}, // 71: fundec ->  fundec_one fundec
     {345, 1}, // 72: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 16} },              
    { {       322}, {  1} }, // program   
    { {       323}, {  2} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {        2} }, 
    { {     EOF__}, { ACCEPT__} }, 
    { {         0}, {        0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, { 13} },          
    { {     296}, { 16} }, // PLUS  
    { {     297}, { 17} }, // MINUS 
    { {     298}, { 18} }, // TIMES 
    { {     299}, { 19} }, // DIVIDE
    { {     290}, { 20} }, // EQ    
    { {     291}, { 21} }, // NEQ   
    { {     293}, { 22} }, // LE    
    { {     292}, { 23} }, // LT    
    { {     294}, { 24} }, // GT    
    { {     295}, { 25} }, // GE    
    { {     289}, { 26} }, // AND   
    { {     288}, { 27} }, // OR    
    { {       0}, { -1} },          
};

SR__ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_6[] =
{
    { { REQ_DEF}, {  4} },          
    { {     270}, { 28} }, // ASSIGN
    { {     269}, { 29} }, // DOT   
    { {     265}, { 30} }, // LBRACK
    { {       0}, { -5} },          
};

SR__ s_7[] =
{
    { { REQ_DEF}, {   5} },          
    { {     342}, {  31} }, // rec   
    { {     265}, {  32} }, // LBRACK
    { {     263}, {  33} }, // LPAREN
    { {     267}, {  34} }, // LBRACE
    { {       0}, { -32} },          
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 35} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 36} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       257}, { 37} }, // ID
    { {         0}, {  0} },      
};

SR__ s_11[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, { 12} },                   
    { {       332}, { 38} }, // decs           
    { {       331}, { 39} }, // decs_nonempty  
    { {       330}, { 40} }, // decs_nonempty_s
    { {       334}, { 41} }, // tydec          
    { {       335}, { 42} }, // vardec         
    { {       344}, { 43} }, // fundec         
    { {       333}, { 44} }, // tydec_one      
    { {       286}, { 45} }, // VAR            
    { {       343}, { 46} }, // fundec_one     
    { {       287}, { 47} }, // TYPE           
    { {       285}, { 48} }, // FUNCTION       
    { {         0}, {  0} },                   
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 49} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, { 17} },                   
    { {       323}, { 50} }, // exp            
    { {       264}, { 51} }, // RPAREN         
    { {       325}, { 52} }, // sequencing_exps
    { {       259}, {  3} }, // INT            
    { {       258}, {  4} }, // STRING         
    { {       284}, {  5} }, // NIL            
    { {       324}, {  6} }, // lvalue         
    { {       257}, {  7} }, // ID             
    { {       272}, {  8} }, // IF             
    { {       275}, {  9} }, // WHILE          
    { {       276}, { 10} }, // FOR            
    { {       283}, { 11} }, // BREAK          
    { {       279}, { 12} }, // LET            
    { {       297}, { 13} }, // MINUS          
    { {       263}, { 14} }, // LPAREN         
    { {       326}, { 15} }, // sequencing     
    { {         0}, {  0} },                   
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 53} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 54} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 55} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 56} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 57} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 58} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 59} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 60} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 61} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 62} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 63} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 64} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 65} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       257}, { 66} }, // ID
    { {         0}, {  0} },      
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 67} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_31[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 68} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_33[] =
{
    { { REQ_DEF}, {  17} },                   
    { {     329}, {  69} }, // actuals        
    { {     328}, {  70} }, // nonemptyactuals
    { {     323}, {  71} }, // exp            
    { {     259}, {   3} }, // INT            
    { {     258}, {   4} }, // STRING         
    { {     284}, {   5} }, // NIL            
    { {     324}, {   6} }, // lvalue         
    { {     257}, {   7} }, // ID             
    { {     272}, {   8} }, // IF             
    { {     275}, {   9} }, // WHILE          
    { {     276}, {  10} }, // FOR            
    { {     283}, {  11} }, // BREAK          
    { {     279}, {  12} }, // LET            
    { {     297}, {  13} }, // MINUS          
    { {     263}, {  14} }, // LPAREN         
    { {     326}, {  15} }, // sequencing     
    { {       0}, { -43} },                   
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  5} },                
    { {       341}, { 72} }, // rec_nonempty
    { {       268}, { 73} }, // RBRACE      
    { {       340}, { 74} }, // rec_one     
    { {       257}, { 75} }, // ID          
    { {         0}, {  0} },                
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       273}, { 76} }, // THEN  
    { {       296}, { 16} }, // PLUS  
    { {       297}, { 17} }, // MINUS 
    { {       298}, { 18} }, // TIMES 
    { {       299}, { 19} }, // DIVIDE
    { {       290}, { 20} }, // EQ    
    { {       291}, { 21} }, // NEQ   
    { {       293}, { 22} }, // LE    
    { {       292}, { 23} }, // LT    
    { {       294}, { 24} }, // GT    
    { {       295}, { 25} }, // GE    
    { {       289}, { 26} }, // AND   
    { {       288}, { 27} }, // OR    
    { {         0}, {  0} },          
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       278}, { 77} }, // DO    
    { {       296}, { 16} }, // PLUS  
    { {       297}, { 17} }, // MINUS 
    { {       298}, { 18} }, // TIMES 
    { {       299}, { 19} }, // DIVIDE
    { {       290}, { 20} }, // EQ    
    { {       291}, { 21} }, // NEQ   
    { {       293}, { 22} }, // LE    
    { {       292}, { 23} }, // LT    
    { {       294}, { 24} }, // GT    
    { {       295}, { 25} }, // GE    
    { {       289}, { 26} }, // AND   
    { {       288}, { 27} }, // OR    
    { {         0}, {  0} },          
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       270}, { 78} }, // ASSIGN
    { {         0}, {  0} },          
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       280}, { 79} }, // IN
    { {         0}, {  0} },      
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_40[] =
{
    { { REQ_DEF}, {  11} },                   
    { {     331}, {  80} }, // decs_nonempty  
    { {     330}, {  40} }, // decs_nonempty_s
    { {     334}, {  41} }, // tydec          
    { {     335}, {  42} }, // vardec         
    { {     344}, {  43} }, // fundec         
    { {     333}, {  44} }, // tydec_one      
    { {     286}, {  45} }, // VAR            
    { {     343}, {  46} }, // fundec_one     
    { {     287}, {  47} }, // TYPE           
    { {     285}, {  48} }, // FUNCTION       
    { {       0}, { -47} },                   
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_44[] =
{
    { { REQ_DEF}, {   4} },             
    { {     334}, {  81} }, // tydec    
    { {     333}, {  44} }, // tydec_one
    { {     287}, {  47} }, // TYPE     
    { {       0}, { -51} },             
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       257}, { 82} }, // ID
    { {         0}, {  0} },      
};

SR__ s_46[] =
{
    { { REQ_DEF}, {   4} },              
    { {     344}, {  83} }, // fundec    
    { {     343}, {  46} }, // fundec_one
    { {     285}, {  48} }, // FUNCTION  
    { {       0}, { -70} },              
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       257}, { 84} }, // ID
    { {         0}, {  0} },      
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       257}, { 85} }, // ID
    { {         0}, {  0} },      
};

SR__ s_49[] =
{
    { { REQ_DEF}, {   3} },          
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {       0}, { -28} },          
};

SR__ s_50[] =
{
    { { REQ_DEF}, {  15} },             
    { {     264}, {  86} }, // RPAREN   
    { {     296}, {  16} }, // PLUS     
    { {     297}, {  17} }, // MINUS    
    { {     298}, {  18} }, // TIMES    
    { {     299}, {  19} }, // DIVIDE   
    { {     290}, {  20} }, // EQ       
    { {     291}, {  21} }, // NEQ      
    { {     293}, {  22} }, // LE       
    { {     292}, {  23} }, // LT       
    { {     294}, {  24} }, // GT       
    { {     295}, {  25} }, // GE       
    { {     289}, {  26} }, // AND      
    { {     288}, {  27} }, // OR       
    { {     262}, {  87} }, // SEMICOLON
    { {       0}, { -36} },             
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       264}, { 88} }, // RPAREN
    { {         0}, {  0} },          
};

SR__ s_53[] =
{
    { { REQ_DEF}, {   3} },          
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {       0}, { -16} },          
};

SR__ s_54[] =
{
    { { REQ_DEF}, {   3} },          
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {       0}, { -17} },          
};

SR__ s_55[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_56[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_57[] =
{
    { { REQ_DEF}, {   5} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {       0}, { -20} },          
};

SR__ s_58[] =
{
    { { REQ_DEF}, {   5} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {       0}, { -21} },          
};

SR__ s_59[] =
{
    { { REQ_DEF}, {   5} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {       0}, { -22} },          
};

SR__ s_60[] =
{
    { { REQ_DEF}, {   5} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {       0}, { -23} },          
};

SR__ s_61[] =
{
    { { REQ_DEF}, {   5} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {       0}, { -24} },          
};

SR__ s_62[] =
{
    { { REQ_DEF}, {   5} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {       0}, { -25} },          
};

SR__ s_63[] =
{
    { { REQ_DEF}, {  11} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {     290}, {  20} }, // EQ    
    { {     291}, {  21} }, // NEQ   
    { {     293}, {  22} }, // LE    
    { {     292}, {  23} }, // LT    
    { {     294}, {  24} }, // GT    
    { {     295}, {  25} }, // GE    
    { {       0}, { -26} },          
};

SR__ s_64[] =
{
    { { REQ_DEF}, {  12} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {     290}, {  20} }, // EQ    
    { {     291}, {  21} }, // NEQ   
    { {     293}, {  22} }, // LE    
    { {     292}, {  23} }, // LT    
    { {     294}, {  24} }, // GT    
    { {     295}, {  25} }, // GE    
    { {     289}, {  26} }, // AND   
    { {       0}, { -27} },          
};

SR__ s_65[] =
{
    { { REQ_DEF}, { 13} },          
    { {     296}, { 16} }, // PLUS  
    { {     297}, { 17} }, // MINUS 
    { {     298}, { 18} }, // TIMES 
    { {     299}, { 19} }, // DIVIDE
    { {     290}, { 20} }, // EQ    
    { {     291}, { 21} }, // NEQ   
    { {     293}, { 22} }, // LE    
    { {     292}, { 23} }, // LT    
    { {     294}, { 24} }, // GT    
    { {     295}, { 25} }, // GE    
    { {     289}, { 26} }, // AND   
    { {     288}, { 27} }, // OR    
    { {       0}, { -9} },          
};

SR__ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       266}, { 89} }, // RBRACK
    { {       296}, { 16} }, // PLUS  
    { {       297}, { 17} }, // MINUS 
    { {       298}, { 18} }, // TIMES 
    { {       299}, { 19} }, // DIVIDE
    { {       290}, { 20} }, // EQ    
    { {       291}, { 21} }, // NEQ   
    { {       293}, { 22} }, // LE    
    { {       292}, { 23} }, // LT    
    { {       294}, { 24} }, // GT    
    { {       295}, { 25} }, // GE    
    { {       289}, { 26} }, // AND   
    { {       288}, { 27} }, // OR    
    { {         0}, {  0} },          
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, { 14} },          
    { {       266}, { 90} }, // RBRACK
    { {       296}, { 16} }, // PLUS  
    { {       297}, { 17} }, // MINUS 
    { {       298}, { 18} }, // TIMES 
    { {       299}, { 19} }, // DIVIDE
    { {       290}, { 20} }, // EQ    
    { {       291}, { 21} }, // NEQ   
    { {       293}, { 22} }, // LE    
    { {       292}, { 23} }, // LT    
    { {       294}, { 24} }, // GT    
    { {       295}, { 25} }, // GE    
    { {       289}, { 26} }, // AND   
    { {       288}, { 27} }, // OR    
    { {         0}, {  0} },          
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       264}, { 91} }, // RPAREN
    { {         0}, {  0} },          
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_71[] =
{
    { { REQ_DEF}, {  14} },          
    { {     260}, {  92} }, // COMMA 
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {     290}, {  20} }, // EQ    
    { {     291}, {  21} }, // NEQ   
    { {     293}, {  22} }, // LE    
    { {     292}, {  23} }, // LT    
    { {     294}, {  24} }, // GT    
    { {     295}, {  25} }, // GE    
    { {     289}, {  26} }, // AND   
    { {     288}, {  27} }, // OR    
    { {       0}, { -40} },          
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       268}, { 93} }, // RBRACE
    { {         0}, {  0} },          
};

SR__ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR__ s_74[] =
{
    { { REQ_DEF}, {   2} },         
    { {     260}, {  94} }, // COMMA
    { {       0}, { -64} },         
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       290}, { 95} }, // EQ
    { {         0}, {  0} },      
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 96} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 97} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, { 15} },              
    { {       323}, { 98} }, // exp       
    { {       259}, {  3} }, // INT       
    { {       258}, {  4} }, // STRING    
    { {       284}, {  5} }, // NIL       
    { {       324}, {  6} }, // lvalue    
    { {       257}, {  7} }, // ID        
    { {       272}, {  8} }, // IF        
    { {       275}, {  9} }, // WHILE     
    { {       276}, { 10} }, // FOR       
    { {       283}, { 11} }, // BREAK     
    { {       279}, { 12} }, // LET       
    { {       297}, { 13} }, // MINUS     
    { {       263}, { 14} }, // LPAREN    
    { {       326}, { 15} }, // sequencing
    { {         0}, {  0} },              
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {  17} },                   
    { {       327}, {  99} }, // expseq         
    { {       325}, { 100} }, // sequencing_exps
    { {       323}, { 101} }, // exp            
    { {       259}, {   3} }, // INT            
    { {       258}, {   4} }, // STRING         
    { {       284}, {   5} }, // NIL            
    { {       324}, {   6} }, // lvalue         
    { {       257}, {   7} }, // ID             
    { {       272}, {   8} }, // IF             
    { {       275}, {   9} }, // WHILE          
    { {       276}, {  10} }, // FOR            
    { {       283}, {  11} }, // BREAK          
    { {       279}, {  12} }, // LET            
    { {       297}, {  13} }, // MINUS          
    { {       263}, {  14} }, // LPAREN         
    { {       326}, {  15} }, // sequencing     
    { {         0}, {   0} },                   
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {   3} },          
    { {       261}, { 102} }, // COLON 
    { {       270}, { 103} }, // ASSIGN
    { {         0}, {   0} },          
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       290}, { 104} }, // EQ
    { {         0}, {   0} },      
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       263}, { 105} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  16} },                   
    { {       325}, { 106} }, // sequencing_exps
    { {       323}, { 101} }, // exp            
    { {       259}, {   3} }, // INT            
    { {       258}, {   4} }, // STRING         
    { {       284}, {   5} }, // NIL            
    { {       324}, {   6} }, // lvalue         
    { {       257}, {   7} }, // ID             
    { {       272}, {   8} }, // IF             
    { {       275}, {   9} }, // WHILE          
    { {       276}, {  10} }, // FOR            
    { {       283}, {  11} }, // BREAK          
    { {       279}, {  12} }, // LET            
    { {       297}, {  13} }, // MINUS          
    { {       263}, {  14} }, // LPAREN         
    { {       326}, {  15} }, // sequencing     
    { {         0}, {   0} },                   
};

SR__ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_90[] =
{
    { { REQ_DEF}, {   2} },      
    { {     282}, { 107} }, // OF
    { {       0}, { -35} },      
};

SR__ s_91[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_92[] =
{
    { { REQ_DEF}, {  17} },                   
    { {     329}, { 108} }, // actuals        
    { {     328}, {  70} }, // nonemptyactuals
    { {     323}, {  71} }, // exp            
    { {     259}, {   3} }, // INT            
    { {     258}, {   4} }, // STRING         
    { {     284}, {   5} }, // NIL            
    { {     324}, {   6} }, // lvalue         
    { {     257}, {   7} }, // ID             
    { {     272}, {   8} }, // IF             
    { {     275}, {   9} }, // WHILE          
    { {     276}, {  10} }, // FOR            
    { {     283}, {  11} }, // BREAK          
    { {     279}, {  12} }, // LET            
    { {     297}, {  13} }, // MINUS          
    { {     263}, {  14} }, // LPAREN         
    { {     326}, {  15} }, // sequencing     
    { {       0}, { -43} },                   
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, {   4} },                
    { {       341}, { 109} }, // rec_nonempty
    { {       340}, {  74} }, // rec_one     
    { {       257}, {  75} }, // ID          
    { {         0}, {   0} },                
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       323}, { 110} }, // exp       
    { {       259}, {   3} }, // INT       
    { {       258}, {   4} }, // STRING    
    { {       284}, {   5} }, // NIL       
    { {       324}, {   6} }, // lvalue    
    { {       257}, {   7} }, // ID        
    { {       272}, {   8} }, // IF        
    { {       275}, {   9} }, // WHILE     
    { {       276}, {  10} }, // FOR       
    { {       283}, {  11} }, // BREAK     
    { {       279}, {  12} }, // LET       
    { {       297}, {  13} }, // MINUS     
    { {       263}, {  14} }, // LPAREN    
    { {       326}, {  15} }, // sequencing
    { {         0}, {   0} },              
};

SR__ s_96[] =
{
    { { REQ_DEF}, {  14} },          
    { {     274}, { 111} }, // ELSE  
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {     290}, {  20} }, // EQ    
    { {     291}, {  21} }, // NEQ   
    { {     293}, {  22} }, // LE    
    { {     292}, {  23} }, // LT    
    { {     294}, {  24} }, // GT    
    { {     295}, {  25} }, // GE    
    { {     289}, {  26} }, // AND   
    { {     288}, {  27} }, // OR    
    { {       0}, { -10} },          
};

SR__ s_97[] =
{
    { { REQ_DEF}, {  13} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {     290}, {  20} }, // EQ    
    { {     291}, {  21} }, // NEQ   
    { {     293}, {  22} }, // LE    
    { {     292}, {  23} }, // LT    
    { {     294}, {  24} }, // GT    
    { {     295}, {  25} }, // GE    
    { {     289}, {  26} }, // AND   
    { {     288}, {  27} }, // OR    
    { {       0}, { -12} },          
};

SR__ s_98[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       277}, { 112} }, // TO    
    { {       296}, {  16} }, // PLUS  
    { {       297}, {  17} }, // MINUS 
    { {       298}, {  18} }, // TIMES 
    { {       299}, {  19} }, // DIVIDE
    { {       290}, {  20} }, // EQ    
    { {       291}, {  21} }, // NEQ   
    { {       293}, {  22} }, // LE    
    { {       292}, {  23} }, // LT    
    { {       294}, {  24} }, // GT    
    { {       295}, {  25} }, // GE    
    { {       289}, {  26} }, // AND   
    { {       288}, {  27} }, // OR    
    { {         0}, {   0} },          
};

SR__ s_99[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {       281}, { 113} }, // END
    { {         0}, {   0} },       
};

SR__ s_100[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_101[] =
{
    { { REQ_DEF}, {  14} },             
    { {     262}, {  87} }, // SEMICOLON
    { {     296}, {  16} }, // PLUS     
    { {     297}, {  17} }, // MINUS    
    { {     298}, {  18} }, // TIMES    
    { {     299}, {  19} }, // DIVIDE   
    { {     290}, {  20} }, // EQ       
    { {     291}, {  21} }, // NEQ      
    { {     293}, {  22} }, // LE       
    { {     292}, {  23} }, // LT       
    { {     294}, {  24} }, // GT       
    { {     295}, {  25} }, // GE       
    { {     289}, {  26} }, // AND      
    { {     288}, {  27} }, // OR       
    { {       0}, { -36} },             
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       257}, { 114} }, // ID
    { {         0}, {   0} },      
};

SR__ s_103[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       323}, { 115} }, // exp       
    { {       259}, {   3} }, // INT       
    { {       258}, {   4} }, // STRING    
    { {       284}, {   5} }, // NIL       
    { {       324}, {   6} }, // lvalue    
    { {       257}, {   7} }, // ID        
    { {       272}, {   8} }, // IF        
    { {       275}, {   9} }, // WHILE     
    { {       276}, {  10} }, // FOR       
    { {       283}, {  11} }, // BREAK     
    { {       279}, {  12} }, // LET       
    { {       297}, {  13} }, // MINUS     
    { {       263}, {  14} }, // LPAREN    
    { {       326}, {  15} }, // sequencing
    { {         0}, {   0} },              
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {   5} },          
    { {       336}, { 116} }, // ty    
    { {       257}, { 117} }, // ID    
    { {       267}, { 118} }, // LBRACE
    { {       271}, { 119} }, // ARRAY 
    { {         0}, {   0} },          
};

SR__ s_105[] =
{
    { { REQ_DEF}, {   5} },                     
    { {     339}, { 120} }, // tyfields         
    { {     338}, { 121} }, // tyfields_nonempty
    { {     337}, { 122} }, // tyfield          
    { {     257}, { 123} }, // ID               
    { {       0}, { -62} },                     
};

SR__ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_107[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       323}, { 124} }, // exp       
    { {       259}, {   3} }, // INT       
    { {       258}, {   4} }, // STRING    
    { {       284}, {   5} }, // NIL       
    { {       324}, {   6} }, // lvalue    
    { {       257}, {   7} }, // ID        
    { {       272}, {   8} }, // IF        
    { {       275}, {   9} }, // WHILE     
    { {       276}, {  10} }, // FOR       
    { {       283}, {  11} }, // BREAK     
    { {       279}, {  12} }, // LET       
    { {       297}, {  13} }, // MINUS     
    { {       263}, {  14} }, // LPAREN    
    { {       326}, {  15} }, // sequencing
    { {         0}, {   0} },              
};

SR__ s_108[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_109[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_110[] =
{
    { { REQ_DEF}, {  13} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {     290}, {  20} }, // EQ    
    { {     291}, {  21} }, // NEQ   
    { {     293}, {  22} }, // LE    
    { {     292}, {  23} }, // LT    
    { {     294}, {  24} }, // GT    
    { {     295}, {  25} }, // GE    
    { {     289}, {  26} }, // AND   
    { {     288}, {  27} }, // OR    
    { {       0}, { -63} },          
};

SR__ s_111[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       323}, { 125} }, // exp       
    { {       259}, {   3} }, // INT       
    { {       258}, {   4} }, // STRING    
    { {       284}, {   5} }, // NIL       
    { {       324}, {   6} }, // lvalue    
    { {       257}, {   7} }, // ID        
    { {       272}, {   8} }, // IF        
    { {       275}, {   9} }, // WHILE     
    { {       276}, {  10} }, // FOR       
    { {       283}, {  11} }, // BREAK     
    { {       279}, {  12} }, // LET       
    { {       297}, {  13} }, // MINUS     
    { {       263}, {  14} }, // LPAREN    
    { {       326}, {  15} }, // sequencing
    { {         0}, {   0} },              
};

SR__ s_112[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       323}, { 126} }, // exp       
    { {       259}, {   3} }, // INT       
    { {       258}, {   4} }, // STRING    
    { {       284}, {   5} }, // NIL       
    { {       324}, {   6} }, // lvalue    
    { {       257}, {   7} }, // ID        
    { {       272}, {   8} }, // IF        
    { {       275}, {   9} }, // WHILE     
    { {       276}, {  10} }, // FOR       
    { {       283}, {  11} }, // BREAK     
    { {       279}, {  12} }, // LET       
    { {       297}, {  13} }, // MINUS     
    { {       263}, {  14} }, // LPAREN    
    { {       326}, {  15} }, // sequencing
    { {         0}, {   0} },              
};

SR__ s_113[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_114[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       270}, { 127} }, // ASSIGN
    { {         0}, {   0} },          
};

SR__ s_115[] =
{
    { { REQ_DEF}, {  13} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {     290}, {  20} }, // EQ    
    { {     291}, {  21} }, // NEQ   
    { {     293}, {  22} }, // LE    
    { {     292}, {  23} }, // LT    
    { {     294}, {  24} }, // GT    
    { {     295}, {  25} }, // GE    
    { {     289}, {  26} }, // AND   
    { {     288}, {  27} }, // OR    
    { {       0}, { -54} },          
};

SR__ s_116[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_117[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_118[] =
{
    { { REQ_DEF}, {   5} },                     
    { {     339}, { 128} }, // tyfields         
    { {     338}, { 121} }, // tyfields_nonempty
    { {     337}, { 122} }, // tyfield          
    { {     257}, { 123} }, // ID               
    { {       0}, { -62} },                     
};

SR__ s_119[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       282}, { 129} }, // OF
    { {         0}, {   0} },      
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       264}, { 130} }, // RPAREN
    { {         0}, {   0} },          
};

SR__ s_121[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_122[] =
{
    { { REQ_DEF}, {   2} },         
    { {     260}, { 131} }, // COMMA
    { {       0}, { -59} },         
};

SR__ s_123[] =
{
    { { REQ_TOKEN}, {   2} },         
    { {       261}, { 132} }, // COLON
    { {         0}, {   0} },         
};

SR__ s_124[] =
{
    { { REQ_DEF}, { 13} },          
    { {     296}, { 16} }, // PLUS  
    { {     297}, { 17} }, // MINUS 
    { {     298}, { 18} }, // TIMES 
    { {     299}, { 19} }, // DIVIDE
    { {     290}, { 20} }, // EQ    
    { {     291}, { 21} }, // NEQ   
    { {     293}, { 22} }, // LE    
    { {     292}, { 23} }, // LT    
    { {     294}, { 24} }, // GT    
    { {     295}, { 25} }, // GE    
    { {     289}, { 26} }, // AND   
    { {     288}, { 27} }, // OR    
    { {       0}, { -7} },          
};

SR__ s_125[] =
{
    { { REQ_DEF}, {  13} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {     290}, {  20} }, // EQ    
    { {     291}, {  21} }, // NEQ   
    { {     293}, {  22} }, // LE    
    { {     292}, {  23} }, // LT    
    { {     294}, {  24} }, // GT    
    { {     295}, {  25} }, // GE    
    { {     289}, {  26} }, // AND   
    { {     288}, {  27} }, // OR    
    { {       0}, { -11} },          
};

SR__ s_126[] =
{
    { { REQ_TOKEN}, {  14} },          
    { {       278}, { 133} }, // DO    
    { {       296}, {  16} }, // PLUS  
    { {       297}, {  17} }, // MINUS 
    { {       298}, {  18} }, // TIMES 
    { {       299}, {  19} }, // DIVIDE
    { {       290}, {  20} }, // EQ    
    { {       291}, {  21} }, // NEQ   
    { {       293}, {  22} }, // LE    
    { {       292}, {  23} }, // LT    
    { {       294}, {  24} }, // GT    
    { {       295}, {  25} }, // GE    
    { {       289}, {  26} }, // AND   
    { {       288}, {  27} }, // OR    
    { {         0}, {   0} },          
};

SR__ s_127[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       323}, { 134} }, // exp       
    { {       259}, {   3} }, // INT       
    { {       258}, {   4} }, // STRING    
    { {       284}, {   5} }, // NIL       
    { {       324}, {   6} }, // lvalue    
    { {       257}, {   7} }, // ID        
    { {       272}, {   8} }, // IF        
    { {       275}, {   9} }, // WHILE     
    { {       276}, {  10} }, // FOR       
    { {       283}, {  11} }, // BREAK     
    { {       279}, {  12} }, // LET       
    { {       297}, {  13} }, // MINUS     
    { {       263}, {  14} }, // LPAREN    
    { {       326}, {  15} }, // sequencing
    { {         0}, {   0} },              
};

SR__ s_128[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       268}, { 135} }, // RBRACE
    { {         0}, {   0} },          
};

SR__ s_129[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       257}, { 136} }, // ID
    { {         0}, {   0} },      
};

SR__ s_130[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {       261}, { 137} }, // COLON
    { {       290}, { 138} }, // EQ   
    { {         0}, {   0} },         
};

SR__ s_131[] =
{
    { { REQ_DEF}, {   5} },                     
    { {     339}, { 139} }, // tyfields         
    { {     338}, { 121} }, // tyfields_nonempty
    { {     337}, { 122} }, // tyfield          
    { {     257}, { 123} }, // ID               
    { {       0}, { -62} },                     
};

SR__ s_132[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       257}, { 140} }, // ID
    { {         0}, {   0} },      
};

SR__ s_133[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       323}, { 141} }, // exp       
    { {       259}, {   3} }, // INT       
    { {       258}, {   4} }, // STRING    
    { {       284}, {   5} }, // NIL       
    { {       324}, {   6} }, // lvalue    
    { {       257}, {   7} }, // ID        
    { {       272}, {   8} }, // IF        
    { {       275}, {   9} }, // WHILE     
    { {       276}, {  10} }, // FOR       
    { {       283}, {  11} }, // BREAK     
    { {       279}, {  12} }, // LET       
    { {       297}, {  13} }, // MINUS     
    { {       263}, {  14} }, // LPAREN    
    { {       326}, {  15} }, // sequencing
    { {         0}, {   0} },              
};

SR__ s_134[] =
{
    { { REQ_DEF}, {  13} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {     290}, {  20} }, // EQ    
    { {     291}, {  21} }, // NEQ   
    { {     293}, {  22} }, // LE    
    { {     292}, {  23} }, // LT    
    { {     294}, {  24} }, // GT    
    { {     295}, {  25} }, // GE    
    { {     289}, {  26} }, // AND   
    { {     288}, {  27} }, // OR    
    { {       0}, { -53} },          
};

SR__ s_135[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_136[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_137[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       257}, { 142} }, // ID
    { {         0}, {   0} },      
};

SR__ s_138[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       323}, { 143} }, // exp       
    { {       259}, {   3} }, // INT       
    { {       258}, {   4} }, // STRING    
    { {       284}, {   5} }, // NIL       
    { {       324}, {   6} }, // lvalue    
    { {       257}, {   7} }, // ID        
    { {       272}, {   8} }, // IF        
    { {       275}, {   9} }, // WHILE     
    { {       276}, {  10} }, // FOR       
    { {       283}, {  11} }, // BREAK     
    { {       279}, {  12} }, // LET       
    { {       297}, {  13} }, // MINUS     
    { {       263}, {  14} }, // LPAREN    
    { {       326}, {  15} }, // sequencing
    { {         0}, {   0} },              
};

SR__ s_139[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_140[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_141[] =
{
    { { REQ_DEF}, {  13} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {     290}, {  20} }, // EQ    
    { {     291}, {  21} }, // NEQ   
    { {     293}, {  22} }, // LE    
    { {     292}, {  23} }, // LT    
    { {     294}, {  24} }, // GT    
    { {     295}, {  25} }, // GE    
    { {     289}, {  26} }, // AND   
    { {     288}, {  27} }, // OR    
    { {       0}, { -13} },          
};

SR__ s_142[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       290}, { 144} }, // EQ
    { {         0}, {   0} },      
};

SR__ s_143[] =
{
    { { REQ_DEF}, {  13} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {     290}, {  20} }, // EQ    
    { {     291}, {  21} }, // NEQ   
    { {     293}, {  22} }, // LE    
    { {     292}, {  23} }, // LT    
    { {     294}, {  24} }, // GT    
    { {     295}, {  25} }, // GE    
    { {     289}, {  26} }, // AND   
    { {     288}, {  27} }, // OR    
    { {       0}, { -69} },          
};

SR__ s_144[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       323}, { 145} }, // exp       
    { {       259}, {   3} }, // INT       
    { {       258}, {   4} }, // STRING    
    { {       284}, {   5} }, // NIL       
    { {       324}, {   6} }, // lvalue    
    { {       257}, {   7} }, // ID        
    { {       272}, {   8} }, // IF        
    { {       275}, {   9} }, // WHILE     
    { {       276}, {  10} }, // FOR       
    { {       283}, {  11} }, // BREAK     
    { {       279}, {  12} }, // LET       
    { {       297}, {  13} }, // MINUS     
    { {       263}, {  14} }, // LPAREN    
    { {       326}, {  15} }, // sequencing
    { {         0}, {   0} },              
};

SR__ s_145[] =
{
    { { REQ_DEF}, {  13} },          
    { {     296}, {  16} }, // PLUS  
    { {     297}, {  17} }, // MINUS 
    { {     298}, {  18} }, // TIMES 
    { {     299}, {  19} }, // DIVIDE
    { {     290}, {  20} }, // EQ    
    { {     291}, {  21} }, // NEQ   
    { {     293}, {  22} }, // LE    
    { {     292}, {  23} }, // LT    
    { {     294}, {  24} }, // GT    
    { {     295}, {  25} }, // GE    
    { {     289}, {  26} }, // AND   
    { {     288}, {  27} }, // OR    
    { {       0}, { -68} },          
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,
};

} // anonymous namespace ends




// If the parsing function call (i.e., parse()' needs arguments, then provide
// an overloaded function.  The code below doesn't rely on parameters, so no
// arguments are required.  Furthermore, parse uses a function try block to
// allow us to do ACCEPT and ABORT from anywhere, even from within members
// called by actions, simply throwing the appropriate exceptions.


// base/base1
ParserBase::ParserBase()
:
    d_token(Reserved__::UNDETERMINED__),
    // $insert baseclasscode
    d_requiredTokens__(0)
{
}

// base/clearin
void ParserBase::clearin__()
{
    d_nErrors__ = 0;
    d_stackIdx = -1;
    d_stateStack.clear();
    d_token = Reserved__::UNDETERMINED__;
    d_next = TokenPair{ Reserved__::UNDETERMINED__, STYPE__{} };
    d_recovery = false;
    d_acceptedTokens__ = d_requiredTokens__;
    d_val__ = STYPE__{};

    push__(0);
}

// base/debugfunctions

void ParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void ParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

// base/lex
void ParserBase::lex__(int token)
{
    d_token = token;

    if (d_token <= 0)
        d_token = Reserved__::EOF__;

    d_terminalToken = true;
}

// base/lookup
int ParserBase::lookup__() const
{
    // if the final transition is negative, then we should reduce by the rule
    // given by its positive value.

    SR__ const *sr = s_state[d_state];
    SR__ const *last = sr + sr->d_lastIdx;

    for ( ; ++sr != last; )           // visit all but the last SR entries
    {
        if (sr->d_token == d_token)
            return sr->d_action;
    }

    if (sr == last)   // reached the last element
    {
        if (sr->d_action < 0)   // default reduction
        {
            return sr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = sr->d_action;


    return action;
}

// base/pop
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx -= count;
    d_state = d_stateStack[d_stackIdx].first;
    d_vsp = &d_stateStack[d_stackIdx];

}

// base/poptoken
void ParserBase::popToken__()
{
    d_token = d_next.first;
    d_val__ = std::move(d_next.second);

    d_next.first = Reserved__::UNDETERMINED__;
}

// base/push
void ParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack.size();
    if (stackSize__() == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack.resize(newSize);
    }

    ++d_stackIdx;
    d_stateStack[d_stackIdx] = 
                    StatePair{ d_state = state, std::move(d_val__) };

    d_vsp = &d_stateStack[d_stackIdx];

    if (d_stackIdx == 0)
    {
    }
    else
    {
    }
}

// base/pushtoken
void ParserBase::pushToken__(int token)
{
    d_next = TokenPair{ d_token, std::move(d_val__) };
    d_token = token;
}

// base/redotoken
void ParserBase::redoToken__()
{
    if (d_token != Reserved__::UNDETERMINED__)
        pushToken__(d_token);
}

// base/reduce
void ParserBase::reduce__(int rule)
{
    PI__ const &pi = s_productionInfo[rule];

    d_token = pi.d_nonTerm;
    pop__(pi.d_size);

    d_terminalToken = false;
}

// base/shift
void ParserBase::shift__(int action)
{
    push__(action);
    popToken__();               // token processed

    if (d_recovery and d_terminalToken)
    {
        d_recovery = false;
        d_acceptedTokens__ = 0;
    }
}

// base/startrecovery
void ParserBase::startRecovery__()
{
    int lastToken = d_token;                // give the unexpected token a
                                            // chance to be processed
                                            // again.

    pushToken__(Reserved__::errTok__);      // specify errTok__ as next token
    push__(lookup__());                     // push the error state

    d_token = lastToken;                    // reactivate the unexpected
                                            // token (we're now in an
                                            // ERROR state).

    d_recovery = true;
}

// base/top
inline size_t ParserBase::top__() const
{
    return d_stateStack[d_stackIdx].first;
}

// derived/errorrecovery
void Parser::errorRecovery__()
{
    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)



    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error();                                // simply skip input
    }

    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, looking up a token allows us to proceed.
    // Continuation may be require multiple reductions, but eventually a
    // terminal-token shift is used. See nextCycle__ for details.

    startRecovery__();
}

// derived/executeaction
void Parser::executeAction__(int production)
try
{
    if (token__() != Reserved__::UNDETERMINED__)
        pushToken__(token__());     // save an already available token
    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 69 "tiger.y"
        {absyn_tree_ = std::make_unique<absyn::AbsynTree>(vs__(0).exp);}
        break;

        case 2:
#line 75 "tiger.y"
        {d_val__.exp = new absyn::IntExp(scanner_.GetTokPos(), vs__(0).ival);}
        break;

        case 3:
#line 76 "tiger.y"
        {d_val__.exp = new absyn::StringExp(scanner_.GetTokPos(), vs__(0).sval);}
        break;

        case 4:
#line 77 "tiger.y"
        {d_val__.exp = new absyn::NilExp(scanner_.GetTokPos());}
        break;

        case 5:
#line 80 "tiger.y"
        {d_val__.exp = new absyn::VarExp(scanner_.GetTokPos(), vs__(0).var);}
        break;

        case 6:
#line 83 "tiger.y"
        {d_val__.exp = new absyn::RecordExp(scanner_.GetTokPos(), vs__(-1).sym, vs__(0).efieldlist);}
        break;

        case 7:
#line 86 "tiger.y"
        {d_val__.exp = new absyn::ArrayExp(scanner_.GetTokPos(), vs__(-5).sym, vs__(-3).exp, vs__(0).exp); }
        break;

        case 8:
#line 89 "tiger.y"
        {d_val__.exp = new absyn::CallExp(scanner_.GetTokPos(), vs__(-3).sym, vs__(-1).explist);}
        break;

        case 9:
#line 92 "tiger.y"
        {d_val__.exp = new absyn::AssignExp(scanner_.GetTokPos(), vs__(-2).var, vs__(0).exp);}
        break;

        case 10:
#line 95 "tiger.y"
        {d_val__.exp = new absyn::IfExp(scanner_.GetTokPos(), vs__(-2).exp, vs__(0).exp, nullptr);}
        break;

        case 11:
#line 96 "tiger.y"
        {d_val__.exp = new absyn::IfExp(scanner_.GetTokPos(), vs__(-4).exp, vs__(-2).exp, vs__(0).exp);}
        break;

        case 12:
#line 99 "tiger.y"
        {d_val__.exp = new absyn::WhileExp(scanner_.GetTokPos(), vs__(-2).exp, vs__(0).exp);}
        break;

        case 13:
#line 100 "tiger.y"
        {d_val__.exp = new absyn::ForExp(scanner_.GetTokPos(), vs__(-6).sym, vs__(-4).exp, vs__(-2).exp, vs__(0).exp);}
        break;

        case 14:
#line 103 "tiger.y"
        {d_val__.exp = new absyn::BreakExp(scanner_.GetTokPos());}
        break;

        case 15:
#line 106 "tiger.y"
        {d_val__.exp = new absyn::LetExp(scanner_.GetTokPos(), vs__(-3).declist, vs__(-1).exp);}
        break;

        case 16:
#line 109 "tiger.y"
        {d_val__.exp = new absyn::OpExp(scanner_.GetTokPos(), absyn::Oper::PLUS_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 17:
#line 110 "tiger.y"
        {d_val__.exp = new absyn::OpExp(scanner_.GetTokPos(), absyn::Oper::MINUS_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 18:
#line 111 "tiger.y"
        {d_val__.exp = new absyn::OpExp(scanner_.GetTokPos(), absyn::Oper::TIMES_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 19:
#line 112 "tiger.y"
        {d_val__.exp = new absyn::OpExp(scanner_.GetTokPos(), absyn::Oper::DIVIDE_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 20:
#line 115 "tiger.y"
        {d_val__.exp = new absyn::OpExp(scanner_.GetTokPos(), absyn::Oper::EQ_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 21:
#line 116 "tiger.y"
        {d_val__.exp = new absyn::OpExp(scanner_.GetTokPos(), absyn::Oper::NEQ_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 22:
#line 117 "tiger.y"
        {d_val__.exp = new absyn::OpExp(scanner_.GetTokPos(), absyn::Oper::LE_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 23:
#line 118 "tiger.y"
        {d_val__.exp = new absyn::OpExp(scanner_.GetTokPos(), absyn::Oper::LT_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 24:
#line 119 "tiger.y"
        {d_val__.exp = new absyn::OpExp(scanner_.GetTokPos(), absyn::Oper::GT_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 25:
#line 120 "tiger.y"
        {d_val__.exp = new absyn::OpExp(scanner_.GetTokPos(), absyn::Oper::GE_OP, vs__(-2).exp, vs__(0).exp);}
        break;

        case 26:
#line 123 "tiger.y"
        {d_val__.exp = new absyn::IfExp(scanner_.GetTokPos(), vs__(-2).exp, vs__(0).exp, new absyn::IntExp(scanner_.GetTokPos(), 0));}
        break;

        case 27:
#line 124 "tiger.y"
        {d_val__.exp = new absyn::IfExp(scanner_.GetTokPos(), vs__(-2).exp, new absyn::IntExp(scanner_.GetTokPos(), 1), vs__(0).exp);}
        break;

        case 28:
#line 127 "tiger.y"
        {d_val__.exp = new absyn::OpExp(scanner_.GetTokPos(), absyn::Oper::MINUS_OP, new absyn::IntExp(scanner_.GetTokPos(), 0), vs__(0).exp);}
        break;

        case 29:
#line 130 "tiger.y"
        {d_val__.exp = vs__(-1).exp;}
        break;

        case 30:
#line 131 "tiger.y"
        {d_val__.exp = new absyn::VoidExp(scanner_.GetTokPos());}
        break;

        case 31:
#line 134 "tiger.y"
        {d_val__.exp = new absyn::SeqExp(scanner_.GetTokPos(), vs__(0).explist);}
        break;

        case 32:
#line 138 "tiger.y"
        {d_val__.var = new absyn::SimpleVar(scanner_.GetTokPos(), vs__(0).sym);}
        break;

        case 33:
#line 139 "tiger.y"
        {d_val__.var = new absyn::FieldVar(scanner_.GetTokPos(), vs__(-2).var, vs__(0).sym);}
        break;

        case 34:
#line 140 "tiger.y"
        {d_val__.var = new absyn::SubscriptVar(scanner_.GetTokPos(), vs__(-3).var, vs__(-1).exp);}
        break;

        case 35:
#line 141 "tiger.y"
        {d_val__.var = new absyn::SubscriptVar(scanner_.GetTokPos(), new absyn::SimpleVar(scanner_.GetTokPos(), vs__(-3).sym), vs__(-1).exp);}
        break;

        case 36:
#line 145 "tiger.y"
        {d_val__.explist = new absyn::ExpList(vs__(0).exp);}
        break;

        case 37:
#line 146 "tiger.y"
        {d_val__.explist = vs__(0).explist; d_val__.explist->Prepend(vs__(-2).exp);}
        break;

        case 38:
#line 150 "tiger.y"
        {d_val__.explist = vs__(-1).explist;}
        break;

        case 39:
#line 154 "tiger.y"
        {d_val__.exp = new absyn::SeqExp(scanner_.GetTokPos(), vs__(0).explist);}
        break;

        case 40:
#line 158 "tiger.y"
        {d_val__.explist = new absyn::ExpList(vs__(0).exp);}
        break;

        case 41:
#line 159 "tiger.y"
        {d_val__.explist = vs__(0).explist; d_val__.explist->Prepend(vs__(-2).exp);}
        break;

        case 42:
#line 163 "tiger.y"
        {d_val__.explist = vs__(0).explist;}
        break;

        case 43:
#line 164 "tiger.y"
        {d_val__.explist = new absyn::ExpList();}
        break;

        case 44:
#line 170 "tiger.y"
        {d_val__.dec = new absyn::TypeDec(scanner_.GetTokPos(), vs__(0).tydeclist);}
        break;

        case 45:
#line 171 "tiger.y"
        {d_val__.dec = vs__(0).dec;}
        break;

        case 46:
#line 172 "tiger.y"
        {d_val__.dec = new absyn::FunctionDec(scanner_.GetTokPos(), vs__(0).fundeclist);}
        break;

        case 47:
#line 177 "tiger.y"
        {d_val__.declist = new absyn::DecList(vs__(0).dec);}
        break;

        case 48:
#line 178 "tiger.y"
        {d_val__.declist = vs__(0).declist; d_val__.declist->Prepend(vs__(-1).dec);}
        break;

        case 49:
#line 183 "tiger.y"
        {d_val__.declist = vs__(0).declist;}
        break;

        case 50:
#line 188 "tiger.y"
        {d_val__.tydec = new absyn::NameAndTy(vs__(-2).sym, vs__(0).ty);}
        break;

        case 51:
#line 193 "tiger.y"
        {d_val__.tydeclist = new absyn::NameAndTyList(vs__(0).tydec);}
        break;

        case 52:
#line 194 "tiger.y"
        {d_val__.tydeclist = vs__(0).tydeclist; d_val__.tydeclist->Prepend(vs__(-1).tydec);}
        break;

        case 53:
#line 199 "tiger.y"
        {d_val__.dec = new absyn::VarDec(scanner_.GetTokPos(), vs__(-4).sym, vs__(-2).sym, vs__(0).exp);}
        break;

        case 54:
#line 200 "tiger.y"
        {d_val__.dec = new absyn::VarDec(scanner_.GetTokPos(), vs__(-2).sym, nullptr, vs__(0).exp);}
        break;

        case 55:
#line 205 "tiger.y"
        {d_val__.ty = new absyn::NameTy(scanner_.GetTokPos(), vs__(0).sym);}
        break;

        case 56:
#line 206 "tiger.y"
        {d_val__.ty = new absyn::RecordTy(scanner_.GetTokPos(), vs__(-1).fieldlist);}
        break;

        case 57:
#line 207 "tiger.y"
        {d_val__.ty = new absyn::ArrayTy(scanner_.GetTokPos(), vs__(0).sym);}
        break;

        case 58:
#line 212 "tiger.y"
        {d_val__.field = new absyn::Field(scanner_.GetTokPos(), vs__(-2).sym, vs__(0).sym);}
        break;

        case 59:
#line 217 "tiger.y"
        {d_val__.fieldlist = new absyn::FieldList(vs__(0).field);}
        break;

        case 60:
#line 218 "tiger.y"
        {d_val__.fieldlist = vs__(0).fieldlist; d_val__.fieldlist->Prepend(vs__(-2).field);}
        break;

        case 61:
#line 223 "tiger.y"
        {d_val__.fieldlist = vs__(0).fieldlist;}
        break;

        case 62:
#line 224 "tiger.y"
        {d_val__.fieldlist = new absyn::FieldList();}
        break;

        case 63:
#line 229 "tiger.y"
        {d_val__.efield = new absyn::EField(vs__(-2).sym, vs__(0).exp);}
        break;

        case 64:
#line 234 "tiger.y"
        {d_val__.efieldlist = new absyn::EFieldList(vs__(0).efield);}
        break;

        case 65:
#line 235 "tiger.y"
        {d_val__.efieldlist = vs__(0).efieldlist; d_val__.efieldlist->Prepend(vs__(-2).efield);}
        break;

        case 66:
#line 240 "tiger.y"
        {d_val__.efieldlist = vs__(-1).efieldlist;}
        break;

        case 67:
#line 241 "tiger.y"
        {d_val__.efieldlist = new absyn::EFieldList();}
        break;

        case 68:
#line 246 "tiger.y"
        {d_val__.fundec = new absyn::FunDec(scanner_.GetTokPos(), vs__(-7).sym, vs__(-5).fieldlist, vs__(-2).sym, vs__(0).exp);}
        break;

        case 69:
#line 247 "tiger.y"
        {d_val__.fundec = new absyn::FunDec(scanner_.GetTokPos(), vs__(-5).sym, vs__(-3).fieldlist, nullptr, vs__(0).exp);}
        break;

        case 70:
#line 252 "tiger.y"
        {d_val__.fundeclist = new absyn::FunDecList(vs__(0).fundec);}
        break;

        case 71:
#line 253 "tiger.y"
        {d_val__.fundeclist = vs__(0).fundeclist; d_val__.fundeclist->Prepend(vs__(-1).fundec);}
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler(exc);
}

// derived/nextcycle
void Parser::nextCycle__()
try
{
    if (s_state[state__()]->d_type & REQ_TOKEN)
        nextToken__();              // obtain next token


    int action = lookup__();        // lookup d_token in d_state

    if (action > 0)                 // SHIFT: push a new state
    {
        shift__(action);
        return;
    }

    if (action < 0)            // REDUCE: execute and pop.
    {

        if (recovery__())
            redoToken__();
        else
            executeAction__(-action);
                                            // next token is the rule's LHS
        reduce__(-action); 
        return;
    }

    if (recovery__())
        ABORT();
    else 
        ACCEPT();
}
catch (ErrorRecovery__)
{
    if (not recovery__())
        errorRecovery__();
    else
    {
        if (token__() == Reserved__::EOF__)
            ABORT();
        popToken__();               // skip the failing token
    }
}


// derived/nexttoken
void Parser::nextToken__()
{ 
    // If d_token is Reserved__::UNDETERMINED__ then if savedToken__() is
    // Reserved__::UNDETERMINED__ another token is obtained from lex(). Then
    // savedToken__() is assigned to d_token.

                                    // no need for a token: got one already
    if (token__() != Reserved__::UNDETERMINED__) 
    {
        return;                             
    }

    if (savedToken__() != Reserved__::UNDETERMINED__)
    {
        popToken__();               // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;       // accept another token (see
                                    // errorRecover())
        lex__(lex());
        print__();
    }
    print();
}

// derived/print
void Parser::print__()
{
// $insert print
}

// derived/parse
int Parser::parse()
try 
{
    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and all relevant variables
    // are initialized by Base::clearin__.
    //
    // Then, in an eternal loop:
    //
    //  1. If a state is a REQ_TOKEN type, then the next token is obtained
    //     from nextToken().  This may very well be the currently available
    //     token. When retrieving a terminal token d_terminal is set to true.
    //
    //  2. lookup() is called, d_token is looked up in the current state's
    //     SR_ array.
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token is not found, and the state has no
    //     default reduction.

    clearin__();                            // initialize, push(0)

    while (true)
    {
// $insert prompt
        nextCycle__();
    }
}
catch (Return__ retValue)
{
    return retValue or d_nErrors__;
}


// derived/tail


